/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityMapRouteImport } from './routes/accessibility-map'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as DemandForecastingRouteImport } from './routes/demand-forecasting'
import { Route as FieldReportsRouteImport } from './routes/field-reports'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as RiskPredictionRouteImport } from './routes/risk-prediction'
import { Route as RouteIntelligenceRouteImport } from './routes/route-intelligence'
import { Route as VehicleTrackingRouteImport } from './routes/vehicle-tracking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityMapRoute = AccessibilityMapRouteImport.update({
  id: '/accessibility-map',
  path: '/accessibility-map',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandForecastingRoute = DemandForecastingRouteImport.update({
  id: '/demand-forecasting',
  path: '/demand-forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldReportsRoute = FieldReportsRouteImport.update({
  id: '/field-reports',
  path: '/field-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskPredictionRoute = RiskPredictionRouteImport.update({
  id: '/risk-prediction',
  path: '/risk-prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteIntelligenceRoute = RouteIntelligenceRouteImport.update({
  id: '/route-intelligence',
  path: '/route-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleTrackingRoute = VehicleTrackingRouteImport.update({
  id: '/vehicle-tracking',
  path: '/vehicle-tracking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility-map': typeof AccessibilityMapRoute
  '/cargo': typeof CargoRoute
  '/demand-forecasting': typeof DemandForecastingRoute
  '/field-reports': typeof FieldReportsRoute
  '/incidents': typeof IncidentsRoute
  '/risk-prediction': typeof RiskPredictionRoute
  '/route-intelligence': typeof RouteIntelligenceRoute
  '/vehicle-tracking': typeof VehicleTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility-map': typeof AccessibilityMapRoute
  '/cargo': typeof CargoRoute
  '/demand-forecasting': typeof DemandForecastingRoute
  '/field-reports': typeof FieldReportsRoute
  '/incidents': typeof IncidentsRoute
  '/risk-prediction': typeof RiskPredictionRoute
  '/route-intelligence': typeof RouteIntelligenceRoute
  '/vehicle-tracking': typeof VehicleTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility-map': typeof AccessibilityMapRoute
  '/cargo': typeof CargoRoute
  '/demand-forecasting': typeof DemandForecastingRoute
  '/field-reports': typeof FieldReportsRoute
  '/incidents': typeof IncidentsRoute
  '/risk-prediction': typeof RiskPredictionRoute
  '/route-intelligence': typeof RouteIntelligenceRoute
  '/vehicle-tracking': typeof VehicleTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility-map'
    | '/cargo'
    | '/demand-forecasting'
    | '/field-reports'
    | '/incidents'
    | '/risk-prediction'
    | '/route-intelligence'
    | '/vehicle-tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility-map'
    | '/cargo'
    | '/demand-forecasting'
    | '/field-reports'
    | '/incidents'
    | '/risk-prediction'
    | '/route-intelligence'
    | '/vehicle-tracking'
  id:
    | '__root__'
    | '/'
    | '/accessibility-map'
    | '/cargo'
    | '/demand-forecasting'
    | '/field-reports'
    | '/incidents'
    | '/risk-prediction'
    | '/route-intelligence'
    | '/vehicle-tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityMapRoute: typeof AccessibilityMapRoute
  CargoRoute: typeof CargoRoute
  DemandForecastingRoute: typeof DemandForecastingRoute
  FieldReportsRoute: typeof FieldReportsRoute
  IncidentsRoute: typeof IncidentsRoute
  RiskPredictionRoute: typeof RiskPredictionRoute
  RouteIntelligenceRoute: typeof RouteIntelligenceRoute
  VehicleTrackingRoute: typeof VehicleTrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility-map': {
      id: '/accessibility-map'
      path: '/accessibility-map'
      fullPath: '/accessibility-map'
      preLoaderRoute: typeof AccessibilityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand-forecasting': {
      id: '/demand-forecasting'
      path: '/demand-forecasting'
      fullPath: '/demand-forecasting'
      preLoaderRoute: typeof DemandForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-reports': {
      id: '/field-reports'
      path: '/field-reports'
      fullPath: '/field-reports'
      preLoaderRoute: typeof FieldReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-prediction': {
      id: '/risk-prediction'
      path: '/risk-prediction'
      fullPath: '/risk-prediction'
      preLoaderRoute: typeof RiskPredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-intelligence': {
      id: '/route-intelligence'
      path: '/route-intelligence'
      fullPath: '/route-intelligence'
      preLoaderRoute: typeof RouteIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-tracking': {
      id: '/vehicle-tracking'
      path: '/vehicle-tracking'
      fullPath: '/vehicle-tracking'
      preLoaderRoute: typeof VehicleTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityMapRoute: AccessibilityMapRoute,
  CargoRoute: CargoRoute,
  DemandForecastingRoute: DemandForecastingRoute,
  FieldReportsRoute: FieldReportsRoute,
  IncidentsRoute: IncidentsRoute,
  RiskPredictionRoute: RiskPredictionRoute,
  RouteIntelligenceRoute: RouteIntelligenceRoute,
  VehicleTrackingRoute: VehicleTrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
